ktor:
  application:
    modules:
      - com.glycin.ApplicationKt.module
  deployment:
    port: "$PORT:9001"
postgres:
  url: "$POSTGRES_URL:jdbc:postgresql://localhost:5432/default"
  user: "$POSTGRES_USER"
  password: "$POSTGRES_PASSWORD"
auth:
  username: "$AUTH_USERNAME"
  password: "$AUTH_PASSWORD"