ktor:
  application:
    modules:
      - com.glycin.ApplicationKt.module
  deployment:
    port: "$PORT:9001"
postgres:
  url: "$POSTGRES_URL:jdbc:postgresql://localhost:5432/default"
  user: "$POSTGRES_USER:username"
  password: "$POSTGRES_PASSWORD:123"
auth:
  username: "$AUTH_USERNAME:admin"
  password: "$AUTH_PASSWORD:admin"